services:
  trino:
    image: trinodb/trino:478
    ports:
    - "8080:8080"
    depends_on:
    - metastore
    - object-store
    volumes:
    - ./lakehouse/trino/etc:/etc/trino
  metastore:
    image: apache/hive:4.2.0
    ports:
      - "9083:9083"
    depends_on:
      - metastore-db
    environment:
      SERVICE_OPTS: "-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=${METASTORE_URL} -Djavax.jdo.option.ConnectionUserName=${METASTORE_USER} -Djavax.jdo.option.ConnectionPassword=${METASTORE_PASSWORD}"
      DB_DRIVER: postgres
    volumes:
      - ${HOME}/.m2/repository/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar:/opt/hive/lib/postgres.jar
  metastore-db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - metastore-data:/var/lib/postgresql/data
  object-store:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
volumes:
  metastore-data:
  